name: Fetch Pull Request Numbers

on:
  push

jobs:
  fetch-pull-requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install curl and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq
      
    - name: Fetch Pull Request Info
      run: |
        curl -s "https://api.github.com/repos/trainee-org/Yash-repo/pulls" \
        -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
        | jq -r '.[] | "\(.title) - \(.html_url)"'
