name: Count Pull Requests

on:
  schedule:
    # Run every day
    - cron: '0 0 * * *'

jobs:
  count-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraphQL
        uses: graphql/github-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Count PRs
        run: |
          query='query { repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") { pullRequests(states: [OPEN]) { totalCount } } }'
          result=$(echo "$query" | graphql)
          prCount=$(echo "$result" | jq -r '.data.repository.pullRequests.totalCount')
          echo "::set-output name=prCount::$prCount"

      - name: Display PR count
        run: echo "Number of PRs:${{ steps.count.outputs.prCount }}"
