name: pr_count

on: push

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Get the reviews count by state kind.
      - name: Get reviews count
        id: reviewsCount
        uses: github-actions-tools/gh-reviews-count@v0.0.1
        with:
          owner: trainee-org
          repo: Yash-repo
          pull_number: ${{ github.event.pull_request.number }} # Use pull_request.number instead of issue.number
      
      - name: Echo reviews count
        run: echo "The approved reviews count is ${{ steps.reviewsCount.outputs.approved }}"
        if: success() && steps.reviewsCount.outputs.approved
