name: pr_count

on: push

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Get the reviews count by state kind.
      - name: Get reviews count
        id: analytics
        uses: AlexSim93/pull-request-analytics-action@v2.2.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          owner: trainee-org
          repo: Yash-repo
      
      - name: Echo reviews count
        run: echo "The approved reviews count is ${{ steps.analytics.outputs.approved }}"
        if: success() && steps.analytics.outputs.approved
