name: Fetch Pull Requests Info

on:
  push
permissions:
  actions: write
  
 
jobs:
  fetch-pull-requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install curl and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq
      
    - name: Fetch Pull Request Info and store in file
      run: |
        curl -s "https://api.github.com/repos/trainee-org/Yash-repo/pulls" \
        -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
        | jq -r '.[] | "\(.title) - \(.html_url)"' > pull_requests_info.txt
        
    - name: Set up Git and set origin URL
      run: |
        git config user.name "github-actions[bot]"
        git config --global user.name "Yashwanth-kumar-s"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
    - name: Commit and push changes
      run: |
         git add .
         git commit -m "generated"
         git push


