name: pr_count

on: push

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Get the reviews count by state kind.
      - name: Get reviews count
        id: analytics
        uses: AlexSim93/pull-request-analytics-action@v2.2.7
        with:
            GITHUB_TOKEN: ${{ secrets.MY_PAT }}
            GITHUB_REPO_FOR_ISSUE: "Yash-repo"
            GITHUB_OWNER_FOR_ISSUE: "trainee-org"
            GITHUB_OWNERS_REPOS: "trainee-org/Yash-repo"
      
      - name: Echo reviews count
        run: echo "The approved reviews count is ${{ steps.analytics.outputs.approved }}"
        if: success() && steps.analytics.outputs.approved
