name: Count Pull Requests

on:
  push

jobs:
  count-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraphQL
        run: |
          PR_COUNT=$(curl -X POST -H "Authorization: bearer ${{ secrets.TOKEN }}" -d '{ "query": "query { repository(owner: \"${{ github.repository_owner }}\", name: \"${{ github.event.repository.name }}\") { pullRequests(states: [OPEN]) { totalCount } } }" }' https://api.github.com/graphql | jq '.data.repository.pullRequests.totalCount')

          echo "Total open pull requests: $PR_COUNT"
