name: Count Pull Requests

on:
  push

jobs:
  count-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR number environment variable
        run: |
          echo "::set-env name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

      - name: Set up GraphQL
        run: |
          PR_DATA=$(curl -X POST -H "Authorization: bearer ${{ secrets.TOKEN }}" -d '{ "query": "query { repository(owner: \"trainee-org\", name: \"Yash-repo\") { pullRequests(states: [OPEN]) { totalCount edges { node { number } } } } }" }' https://api.github.com/graphql | jq '.data.repository.pullRequests')

          PR_COUNT=$(echo $PR_DATA | jq '.totalCount')
          PR_NUMBERS=$(echo $PR_DATA | jq -r '.edges[].node.number')

          echo "Total open pull requests: $PR_COUNT"
          echo "Pull request numbers: $PR_NUMBERS"
